### ISSUE TITLE
Stuttering

### ISSUE THREAD

**Issue by AtomicLN** [Zolika1351/ChaosModGTASA#1]
For some reason with a high PC and mods that fix some bugs of the game, my game runs Normaly but with this script just giveme some Stuttering like each 2 seconds.

**Comment by eriel222** [comment]
Same issue. Tried light-modded and vanilla GTA. Game stutters at both versions. My PC is not high-end but game runs smooth

**Comment by Zolika1351** [comment]
Today's update should've fixed it, let me know if it did

**Comment by Imflyin2023** [comment]
> Today's update should've fixed it, let me know if it did

Do you know how to make this work on the Definitive Edition? I have CLEO Redux and Ultimate Asi Loader installed in the latest versions, I added all the files from Zchaos [except the if not using CLEO folder] to Gameface\Binaries\Win64\ after that I pressed F7 in the game and it doesn't work...

**Comment by Zolika1351** [comment]
> Do you know how to make this work on the Definitive Edition?

I don't support worthless trash "remasters" that are objectively worse than the original in every way

**Comment by Imflyin2023** [comment]
> I don't support worthless trash "remasters" that are objectively worse than the original in every way

Yes, I understand you, but I would still like to play such great mods like Tightened Thrice, Tightened Vice and not only on the Definitive Edition, but adding Main.SCM from these mods will cause a crash when trying to start a new game, and I was told that it needs to be created from scratch.
